<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <AssemblyName>Oxide.Ext.ConsoleExt</AssemblyName>
        <RootNamespace>Oxide.Ext.ConsoleExt</RootNamespace>

        <!-- Removes the .pdb file from the output folder. -->
        <DebugType>embedded</DebugType>
    </PropertyGroup>
</Project>
