<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>Oxide.Plugins</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ConsoleExt\ConsoleExt.csproj" ReferenceOutputAssembly="true" Private="false" />
    </ItemGroup>

</Project>
