name: Create Release

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    uses: ilovepatatos-rust/github-workflows/.github/workflows/release.yml@main
    with:
      project: src/ConsoleExt/ConsoleExt.csproj
      asset: Oxide.Ext.ConsoleExt.dll, Carbon.Ext.ConsoleExt.dll
      targets: oxide, carbon
      publicize: false
      keep_versions: 3
    secrets: inherit
