name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0 # Necessary to fetch all tags for version calculation

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2

    - name: Download References
      shell: pwsh
      run: .\rust-dependencies-download.ps1

    - name: Restore NuGet packages
      run: msbuild -t:restore src/ConsoleExt/ConsoleExt.csproj /p:Platform=Oxide

    - name: Build Oxide DLL
      run: msbuild src/ConsoleExt/ConsoleExt.csproj /p:Configuration=Release /p:Platform=Oxide

    - name: Build Carbon DLL
      run: msbuild src/ConsoleExt/ConsoleExt.csproj /p:Configuration=Release /p:Platform=Carbon

    - name: Automated Versioning
      if: github.ref == 'refs/heads/main'
      run: |
        git fetch --tags
        $latestTag = git tag -l --sort=-v:refname | Select-Object -First 1
        if (-not $latestTag) {
          $latestTag = "v1.0.0"
        }
        $versionNumbers = $latestTag.TrimStart('v').Split('.')
        $newPatch = [int]$versionNumbers[2] + 1
        $newTag = "v{0}.{1}.{2}" -f $versionNumbers[0], $versionNumbers[1], $newPatch
        git tag $newTag
        git push origin $newTag
        echo "New Tag: $newTag"
        echo "NEW_TAG=$newTag" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      run: |
        gh release create ${{ env.NEW_TAG }} "src\ConsoleExt\bin\Oxide\Release\net48\Oxide.Ext.ConsoleExt.dll" "src\ConsoleExt\bin\Carbon\Release\net48\Carbon.Ext.ConsoleExt.dll" --title "Release ${{ env.NEW_TAG }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
